config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :orders
  resources :menus
  resources :order_items
  resources :menu_items
  resources :admins

  patch "menu/edit_menu_details" => "menus#edit_menu_details", as: :edit_menu_details
  patch "menu_item/edit_menu_items_details" => "menu_items#edit_menu_item_details", as: :edit_menu_item_details
  get "admin/manage_billers" => "admins#manage_billers", as: :manage_billers
  get "admin/new_clerk" => "admins#new_clerk", as: :new_clerk
  post "admin/create_clerk" => "admins#create_clerk", as: :create_clerk
  get "admin/users" => "admins#users", as: :show_users
  get "admin/reports" => "admins#reports", as: :show_reports
  delete "admin/delete_user" => "admins#delete_user", as: :delete_user
  patch "admin/role_clerk" => "admins#role_change_clerk", as: :role_change_clerk
  patch "admin/role_customer" => "admins#role_change_customer", as: :role_change_customer
  get "/order/pending" => "orders#pending", as: :pending_orders
  get "/" => "home#index"
  post "/cart" => "orders#cart"
  get "/active" => "menus#active_menus", as: :active_menus
  post "/signin" => "sessions#create", as: :sessions
  get "/signin" => "sessions#new", as: :new_sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  validates :name, presence: true
  has_many :menu_items, dependent: :destroy

  def self.active
    all.where(active: true)
  end
end

app/models/menus.rb
class Menu < ApplicationRecord
  validates :name, presence: true
  has_many :menu_items
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
    @current_user = current_user
    @menus = Menu.active
    render "index"
  end

  def new
    render "new"
  end

  def show
    if @current_user == nil
      @current_user = current_user
    end
    render "show"
  end

  def create
    name = params[:name]
    new_menu = Menu.new(name: name, active: false)
    if new_menu.save
      redirect_to new_menu_path
    else
      flash[:error] = new_menu.errors.full_messages.join(",")
      redirect_to new_menu_path
    end
  end

  def destroy
    id = params[:id]
    Menu.find(id).destroy
    redirect_to new_menu_path
  end

  def edit
    id = params[:id]
    session[:edit_menu_id] = id
    redirect_to new_menu_path
  end

  def update
    id = params[:id]
    menu = Menu.find(id)
    menu.active = !menu.active
    if menu.save
      redirect_to new_menu_path
    end
  end

  def edit_menu_details
    id = params[:id]
    new_name = params[:name]
    menu = Menu.find(id)
    menu.name = new_name
    if menu.save
      session[:edit_menu_id] = -1
    else
      flash[:error] = menu.errors.full_messages.join(",")
    end
    redirect_to new_menu_path
  end
end

app/views/menus/index.html.erb
<section>
  <h2> Menus </h2>
  <% counter = 0 %>
    <% @menus.each do |menu| %>
        <%= link_to menu_path(menu.id) do %>
          <%= menu.name %>
        <% end %>
        <% counter = counter + 1 %>
    <% end %>
</section>

app/views/menus/new.html.erb
<article>
  <div>
    <%= form_with(url: "/menus", method: "post", class: "AddMenu") do %>
      <%= text_field_tag "name", nil, placeholder: "Name of the Menu?", class: "AddMenu-name" %>
      <%= submit_tag "Add", class: "AddMenu-button" %>
    <% end %>
  </div>
  <div class="Menus">
    <% Menu.all.each do |menu| %>
        <% if session[:edit_menu_id].to_s == (menu.id).to_s %>
          <div class="EditMenu">
            <%= form_with url: edit_menu_details_path, method: "patch" do %>
              <%= hidden_field_tag :id, menu.id %>
              <%= text_field_tag :name, menu.name, placeholder: "Change the Menu Name", class: "AddMenu-name" %>
              <%= submit_tag "change name", class: "Table-button" %>
            <% end %>
          </div>
        <% else %>
            <div class="EditMenu">
              <%= link_to menu_path(menu.id), method: "patch" do %>
              <%= hidden_field_tag :id, menu.id %>
              <%= check_box_tag "active", "1", checked = menu.active, class: "Menu-checkbox", onclick: "this.form.submit()" %>
              <% end %>
              <p class="EditMenu-name"> <%= menu.name %> </p>
              <%= form_with(url: edit_menu_path(menu.id), method: "get", local: true) do %>
                <%= hidden_field_tag :id, menu.id %>
                <%= image_submit_tag "edit.svg", class: "edit", title: "Edit MenuName" %>
              <% end %>
              <% if menu.active %>
                <p class="Menu-active">Active</p>
              <% else %>
                <p class="Menu-Inactive">InActive</p>
              <% end %>
              <%= form_with(url: menu_item_path(menu.id), method: "get", local: true) do %>
                <%= image_submit_tag "plus-solid.svg", class: "plus-img", title: "Edit Menu content" %>
              <% end %>
              <%= form_with url: menu_path(menu.id), method: "delete", class: "Menu-form" do |form| %>
                <%= image_submit_tag "trash.svg", data: { confirm: "Are you sure?" }, class: "EditMenu-img", title: "Delete Menu" %>
              <% end %>
            </div>
        <% end %>
    <% end %>
  </div>
</article>

app/views/menus/show.html.erb
<% menu = Menu.find(params[:id]).menu_items %>
<% menu_id = params[:id] %>
<article class="Wrapper">
    <section class="Wrapper-grid">
      <section class="MenuItem">
          <% menu.each do |item| %>
            <div class="MenuItem-container">
              <%= form_with url: cart_path, method: "post" do |form| %>
                <%= hidden_field_tag :item_name, item.menu_item_name %>
                <%= hidden_field_tag :item_price, item.menu_item_price %>
                <%= hidden_field_tag :menu_item_id, item.id %>
                <%= hidden_field_tag :menu_id, menu_id %>
                <p class="MenuItem-name HeaderFont"> <%= item.menu_item_name %> </p>
                <div class="LeftRight">
                <p class="MenuItem-price"> Price: &#x20b9; <%= item.menu_item_price %> </p>
                <div style="display:flex;">
                  <p style="margin-right:10px;">Quantity: </p>
                  <input type="number" name="quantity" id="quantity" value="1" min="1" max="8">
                </div>
                </div>
                <div class="wrapper">
                  <%= form.submit "Add to Cart", class: "Table-button" %>
                </div>
              <% end %>
            </div>
          <% end %>
      </section>
      <section class="Food-cart">
        <h1 style="font-size:x-large;padding-bottom:10px;" class="HeaderFont">Your Cart!</h1>
        <% order_items = Order.find(@current_order.id).order_items %>
        <% total_price = 0 %>
        <div class="Item-info">
          <% if order_items.length != 0 %>
              <p class="HeaderFont">S.No</p>
              <p class="HeaderFont">Item</p>
              <p class="HeaderFont">Price</p>
              <p class="HeaderFont">Quantity</p>
              <p class="HeaderFont">Total Price</p>
              <p></p>
          <% end %>
          <% item_count = 1 %>
          <% order_items.each do |item| %>
              <p> <%= item_count %> </p>
              <p> <%= item.menu_item_name %> </p>
              <p> &#x20b9; <%= item.menu_item_price %> </p>
              <p> <%= item.quantity %> </p>
              <p> &#x20b9; <%= item.price %> </p>
              <%= form_with url: order_item_path(item.id), method: "delete" do %>
                <%= hidden_field_tag :menu_id, menu_id %>
                <%= image_submit_tag "minus.svg", class: "Minus" %>
              <% end %>
            <% item_count = item_count + 1 %>
            <% total_price += item.price %>
          <% end %>
        </div>
        <% if order_items.length != 0 %>
          <p style="padding:10px;">Total Price: &#x20b9; <%= total_price %> </p>
          <%= form_with url: orders_path, method: "post" do |form| %>
            <%= hidden_field_tag :total_price, total_price %>

            <%= submit_tag value = "Buy Now",
                           data: { confirm: "Confirm Order?", disable_with: "Placing Order.." },
                           class: "Table-button" %>
          <% end %>
        <% else %>
          <p>Add Your Items here..!</p>
         <% end %>
      </section>
    </section>
</article>