config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :orders
  resources :menus
  resources :order_items
  resources :menu_items
  resources :admins

  patch "menu/edit_menu_details" => "menus#edit_menu_details", as: :edit_menu_details
  patch "menu_item/edit_menu_items_details" => "menu_items#edit_menu_item_details", as: :edit_menu_item_details
  get "admin/manage_billers" => "admins#manage_billers", as: :manage_billers
  get "admin/new_clerk" => "admins#new_clerk", as: :new_clerk
  post "admin/create_clerk" => "admins#create_clerk", as: :create_clerk
  get "admin/users" => "admins#users", as: :show_users
  get "admin/reports" => "admins#reports", as: :show_reports
  delete "admin/delete_user" => "admins#delete_user", as: :delete_user
  patch "admin/role_clerk" => "admins#role_change_clerk", as: :role_change_clerk
  patch "admin/role_customer" => "admins#role_change_customer", as: :role_change_customer
  get "/order/pending" => "orders#pending", as: :pending_orders
  get "/" => "home#index"
  post "/cart" => "orders#cart"
  get "/active" => "menus#active_menus", as: :active_menus
  post "/signin" => "sessions#create", as: :sessions
  get "/signin" => "sessions#new", as: :new_sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
end

app/views/admins/biller.html.erb
<article>
  <p class="ChangeFont" style="padding-top:20px;">Billers</p>
  <%= link_to new_clerk_path, method: "get" do %>
    <%= image_tag "user_icon.png", class: "AddUserImg", title: "Add Biller" %>
  <% end %>
  <div class="Menus" style="padding:10px;">
    <% count = 1 %>
    <% @billers.all.each do |clerk| %>
      <div class="EditMenu">
        <p> <%= count %>. </p>
        <p class="EditMenu-name"> <%= clerk.first_name.to_s + clerk.last_name.to_s %> </p>
        <p class="EditMenu-name"> <%= clerk.email %> </p>
        <%= form_with(url: user_path(clerk.id), method: "delete", class: "Menu-form") do |form| %>
          <%= image_submit_tag "trash.svg", class: "EditMenu-img", title: "Delete User", data: { confirm: "Are you sure?" } %>
        <% end %>
        <% count = count + 1 %>
      </div>
    <% end %>
  </div>
</article>

app/views/admins/new_clerk.html.erb
<section style="margin-top:20px;">
  <p style="padding-top:20px;" class="ChangeFont">New Biller</p>
  <div class="NewClerk">
    <%= form_with url: create_clerk_path do |form| %>
      <div class="Form-section">
        <p class="FormInput-label">First name:</p>
        <%= form.text_field :first_name, class: "Form-input" %>
      </div>
      <div class="Form-section">
        <p class="FormInput-label">Last name:</p>
        <%= form.text_field :last_name, class: "Form-input" %>
      </div>
      <div class="Form-section">
        <p class="FormInput-label">email:</p>
        <%= form.email_field :email, class: "Form-input" %>
      </div>
      <div class="Form-section">
        <p class="FormInput-label">password:</p>
        <%= form.password_field :password, class: "Form-input" %>
      </div>
      <div class="Form-section">
        <%= form.submit "CREATE", class: "Form-submit" %>
      </div>
    <% end %>
  </div>
</section>

app/views/admins/reports.html.erb
<div class="ReportsFilter">
  <div style="margin-top:30px;">
    <%= form_with(url: show_reports_path, method: "get", local: true) do %>
      <%= label_tag :from_date, "From Date: " %>
      <%= date_field_tag :from_date, @from_date, class: "FilterItem" %>
      <%= label_tag :to_date, "To Date: " %>
      <%= date_field_tag :to_date, @to_date, class: "FilterItem" %>
     <%= submit_tag "Apply", class: "Table-button" %>
    <% end %>
  </div>
</div>
<section>
  <% if @invoices.empty? %>
    <p style="position:absolute;font-size:30px;top:40%;left:40%;color:#ac4d62;font-style:Italic;">
      No Invoices in that period!
    </p>
  <% else %>
    <div class="EditMenu" style="background-color:#abcd34;margin-top:20px;">
      <p>ORDER ID</p>
      <p>USER NAME</p>
      <p>ORDER TYPE</p>
      <p>ORDER PRICE</p>
      </div>
    <div>
    <% @invoices.each do |invoice| %>
      <div class="EditMenu">
      <p> <%= invoice.id %> </p>
      <p></p>
      <p> <%= invoice.user.first_name.to_s + invoice.user.last_name.to_s %> </p>
      <p></p>
      <p> <%= invoice.order_type %> </p>
      <p></p>
      <p></p>
      <p>&#x20b9; <%= invoice.total_price %> </p>
      <%= form_with url: order_path(invoice.id), method: "get", local: true do %>
        <%= image_submit_tag "enter.svg", class: "Enter-img", title: "View Invoice" %>
      <% end %>
      </div>
    <% end %>
  <% end %>
</section>

app/views/admins/user.html.erb
<section style="padding-top:20px;">
  <% if !@admins.empty? %>
    <p class="ChangeFont">Owners</p>
  <% end %>
  <% count = 1 %>
  <% @admins.each do |admin| %>
    <div class="EditMenu">
      <p> <%= count %>. </p>
      <p> <%= admin.first_name.to_s + admin.last_name.to_s %> </p>
      <p> <%= admin.email %> </p>
    </div>
    <% count = count + 1 %>
  <% end %>
  <% count = 1 %>
  <% if !@billers.empty? %>
    <p class="ChangeFont">Billers</p>
  <% end %>
  <% @billers.each do |clerk| %>
    <div class="EditMenu">
      <p> <%= count %>. </p>
      <p> <%= clerk.first_name.to_s + clerk.last_name.to_s %> </p>
      <p> <%= clerk.email %> </p>
      <%= form_with url: delete_user_path, method: "delete", class: "Menu-form" do |form| %>
        <%= hidden_field_tag :user_id, clerk.id %>
        <%= image_submit_tag "trash.svg", data: { confirm: "Are you sure?" }, class: "Delete-img", title: "Delete User" %>
      <% end %>
      <%= form_with(url: role_change_customer_path, method: "patch", local: true) do %>
        <%= hidden_field_tag :user_id, clerk.id %>
        <%= image_submit_tag "role-change.png", class: "RoleChange", title: "Assign customer role" %>
      <% end %>
    </div>
    <% count = count + 1 %>
  <% end %>
  <% count = 1 %>
  <% if !@customers.empty? %>
    <p class="ChangeFont">Customers</p>
  <% end %>
  <% @customers.each do |customer| %>
    <div class="EditMenu">
      <p> <%= count %>. </p>
      <p> <%= customer.first_name.to_s + customer.last_name.to_s %> </p>
      <p> <%= customer.email %> </p>
      <%= form_with(url: role_change_clerk_path, method: "patch", local: true) do %>
        <%= hidden_field_tag :user_id, customer.id %>
        <%= image_submit_tag "role-change.png", class: "RoleChange", title: "Assign clerk role" %>
      <% end %>
    </div>
    <% count = count + 1 %>
  <% end %>
</section>