config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :orders
  resources :menus
  resources :order_items
  resources :menu_items
  resources :admins

  patch "menu/edit_menu_details" => "menus#edit_menu_details", as: :edit_menu_details
  patch "menu_item/edit_menu_items_details" => "menu_items#edit_menu_item_details", as: :edit_menu_item_details
  get "admin/manage_billers" => "admins#manage_billers", as: :manage_billers
  get "admin/new_clerk" => "admins#new_clerk", as: :new_clerk
  post "admin/create_clerk" => "admins#create_clerk", as: :create_clerk
  get "admin/users" => "admins#users", as: :show_users
  get "admin/reports" => "admins#reports", as: :show_reports
  delete "admin/delete_user" => "admins#delete_user", as: :delete_user
  patch "admin/role_clerk" => "admins#role_change_clerk", as: :role_change_clerk
  patch "admin/role_customer" => "admins#role_change_customer", as: :role_change_customer
  get "/order/pending" => "orders#pending", as: :pending_orders
  get "/" => "home#index"
  post "/cart" => "orders#cart"
  get "/active" => "menus#active_menus", as: :active_menus
  post "/signin" => "sessions#create", as: :sessions
  get "/signin" => "sessions#new", as: :new_sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  validates :menu_id, presence: true
  validates :menu_item_name, presence: true
  validates :menu_item_price, presence: true
  belongs_to :menu
end

app/models/menu_items.rb
class MenuItem < ActiveRecord::Base
  validates :menu_id, presence: true
  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true
  belongs_to :menu
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  def index
  end

  def create
    id = params[:menu_id]
    item_name = params[:menu_item_name]
    item_price = params[:menu_item_price]
    new_menu_item = MenuItem.new(menu_id: id, menu_item_name: item_name, menu_item_price: item_price)
    if new_menu_item.save
      redirect_to menu_item_path(id)
    else
      flash[:error] = new_menu_item.errors.full_messages.join(",")
      redirect_to menu_item_path(id)
    end
  end

  def edit
    session[:edit_menu_item_id] = params[:id]
    redirect_to menu_item_path(params[:menu_id])
  end

  def show
    @menu_id = params[:id]
    @menu_items = Menu.find(@menu_id).menu_items
    render "show"
  end

  def destroy
    id = params[:id]
    menu_id = MenuItem.find(id).menu_id
    MenuItem.find(id).destroy
    redirect_to menu_item_path(params[:menu_id])
  end

  def edit_menu_item_details
    id = params[:menu_item_id]
    new_name = params[:menu_item_name]
    new_price = params[:menu_item_price]
    menu_item = MenuItem.find(id)
    menu_item.menu_item_name = new_name
    menu_item.menu_item_price = new_price
    if menu_item.save
      session[:edit_menu_item_id] = -1
    else
      flash[:error] = menu_item.errors.full_messages.join(",")
    end
    redirect_to menu_item_path(params[:menu_id])
  end
end

app/views/menu_items/show.html.erb
<article>
  <div>
    <%= form_with url: menu_items_path, method: "post", class: "AddMenuItem" do %>
      <%= hidden_field_tag :menu_id, @menu_id %>
      <%= text_field_tag "menu_item_name", nil, placeholder: "Name of the MenuItem", class: "AddMenuItem-name" %>
      <input type="number" name="menu_item_price" value="100" min="1" max="1000" class="AddMenuItem-price"/>
      <%= submit_tag "Add", class: "AddMenu-button" %>
    <% end %>
  </div>
  <div>
    <% @menu_items.each do |menu_item| %>
      <% if session[:edit_menu_item_id].to_s == (menu_item.id).to_s %>
        <div class="EditMenu">
        <%= form_with url: edit_menu_item_details_path, method: "patch" do %>
          <%= hidden_field_tag :menu_id, @menu_id %>
          <%= hidden_field_tag :menu_item_id, menu_item.id %>
          <%= text_field_tag "menu_item_name",
                             menu_item.menu_item_name,
                             placeholder: "Change the MenuItem Name",
                             class: "AddMenuItem-name" %>
          <input type="number" name="menu_item_price" value=<%= menu_item.menu_item_price %> min="1" max="1000" class="AddMenuItem-price"/>
          <%= submit_tag "Change" %>
        <% end %>
        </div>
      <% else %>
        <div class="EditMenuItem">
          <p class="EditMenuItem-name"> <%= menu_item.menu_item_name %> </p>
          <p> &#x20b9; <%= menu_item.menu_item_price %> </p>
          <%= form_with(url: edit_menu_item_path(menu_item.id), method: "get", local: true) do %>
              <%= hidden_field_tag :menu_id, @menu_id %>
              <%= image_submit_tag "edit.svg", class: "edit", title: "Edit MenuName" %>
          <% end %>
          <%= form_with url: menu_item_path(menu_item.id), method: "delete", class: "Menu-form" do %>
            <%= hidden_field_tag :menu_id, @menu_id %>
            <%= image_submit_tag "trash.svg", class: "EditMenu-img", data: { confirm: "Are you sure?" } %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</article>