config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :orders
  resources :menus
  resources :order_items
  resources :menu_items
  resources :admins

  patch "menu/edit_menu_details" => "menus#edit_menu_details", as: :edit_menu_details
  patch "menu_item/edit_menu_items_details" => "menu_items#edit_menu_item_details", as: :edit_menu_item_details
  get "admin/manage_billers" => "admins#manage_billers", as: :manage_billers
  get "admin/new_clerk" => "admins#new_clerk", as: :new_clerk
  post "admin/create_clerk" => "admins#create_clerk", as: :create_clerk
  get "admin/users" => "admins#users", as: :show_users
  get "admin/reports" => "admins#reports", as: :show_reports
  delete "admin/delete_user" => "admins#delete_user", as: :delete_user
  patch "admin/role_clerk" => "admins#role_change_clerk", as: :role_change_clerk
  patch "admin/role_customer" => "admins#role_change_customer", as: :role_change_customer
  get "/order/pending" => "orders#pending", as: :pending_orders
  get "/" => "home#index"
  post "/cart" => "orders#cart"
  get "/active" => "menus#active_menus", as: :active_menus
  post "/signin" => "sessions#create", as: :sessions
  get "/signin" => "sessions#new", as: :new_sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CafeteriaManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
    <link
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      rel="stylesheet"
      type="text/css"
    />
  </head>

  <body>
    <% if @current_user %>

      <div class="NavBar">
          <ul class="NavBar-items">
            <li class="NavBar-title">
              <p style="font-size: xxx-large;color:dimgrey;">Cafeteria</p>
            <li>
            <% if @current_user.role == "owner" %>
              <li class="NavBar-item-wrapper">
                <i class="fa fa-home"></i>
                <%= link_to "Home", new_menu_path, method: "get", class: "NavBar-content" %>
              </li>
              <li class="NavBar-item-wrapper">
                <%= link_to "Users", show_users_path, method: "get", class: "NavBar-content" %>
              </li>
              <li class="NavBar-item-wrapper">
                <%= link_to "Manage Billers", manage_billers_path, method: "get", class: "NavBar-content" %>
              </li>
              <li class="NavBar-item-wrapper">
                <%= link_to "Reports", show_reports_path, method: "get", class: "NavBar-content" %>
              </li>
            <% end %>
            <% if (@current_user.role == "owner" || @current_user.role == "clerk") %>
              <li class="NavBar-item-wrapper">
                  <i class="fa fa-truck"></i>
                  <%= link_to "Pending-orders", pending_orders_path, method: "get", class: "NavBar-content" %>
              </li>
            <% end %>
            <li class="NavBar-item-wrapper">
              <i class="fa fa-hamburger"></i>
              <%= link_to "Menus", menus_path, method: "get", class: "NavBar-content" %>
            </li>
            <li class="NavBar-item-wrapper">
              <%= link_to "My-Orders", orders_path, method: "get", class: "NavBar-content" %>
            </li>
            <li class="NavBar-item-wrapper">
              <i class="fa fa-power-off"></i>
              <%= link_to "Sign-out", destroy_session_path, method: "delete", class: "NavBar-content" %>
            </li>
            <div class="dropdown">
              <div class="a:hover">
                <a href="/users/<%= session[:current_user_id] %>">Profile</a>
              </div>
            </div>
          </ul>
      </div>
    <% end %>
    <div class="Body-content">
      <% if flash[:error] %>
        <p class="Flash-error">
          <%= flash[:error] %>
        </p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>